#hair_eye_color Data set----
h1=read.csv("hair_eye_color_csv.csv")
cat("\nHair Eye Color Dataset")
ebb=sum(h1$Eye.Color=='Brown')
cat("\nTotal ppl with Brown eyes:",ebb)
ehb=sum(h1$Hair.Color=='Blonde')#nrow(h1[which(h1$Hair.Color=='Blonde'),])
cat("\nTotal ppl with Brown eyes:",ehb)
ebbl=sum(h1$Eye.Color=='Black')#nrow(h1[which(h1$Eye.Color=='Black'),])
cat("\nTotal ppl with Black eyes:",ebbl)
ebhb=sum(h1$Eye.Color=='Black' & h1$Hair.Color=='Brown')#nrow(h1[which(h1$Eye.Color=='Black' & h1$Hair.Color=='Brown'),])
cat("\nTotal ppl with Brown eyes:",ebhb)
nh1=nrow(h1)
perc1=100*(sum(h1$Eye.Color=="Green")/nh1)
cat("\n% of people with Green eyes:",perc1,"%")
perc2=100*(sum(h1$Eye.Color=='Blue' & h1$Hair.Color=='Red')/nh1)
cat("\n% of people with Blue eyes and Red hair:",perc2,"%")
